version: "3.2"
services:
  # NOTICE: AOF and RDB needs to be at /tmp/redis/local-data,ACL needs to be set at the client
  redis-stack:
    image: redis-stack:6.2.6-v10
    environment:
      - CONFFILE=etc/redis-stack.conf
      - REDIS_ARGS="--logfile redis.log"
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
        - /tmp/redis/local-data:/data
  # NOTICE: 4 ENV variables are required for the following services,you can define them in web-variables.env
  mysql:
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./web-variables.env
    volumes:
      - /tmp/mysql/data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
  # NOTICE: you should deploy the 1st website at /tmp/nginx/html/admin,the 2nd at /tmp/nginx/html/doctor
  nginx:
    image: nginx:latest
    ports:
      - "5672:5672"
      - "5173:5173"
      - "8858:8858"
    volumes:
      - /tmp/nginx/conf:/etc/nginx
      - /tmp/nginx/logs:/var/log/nginx
      - /tmp/nginx/html:/usr/share/nginx/html
#  elastic-search:
#    container_name: es
#    image: elasticsearch:7.12.1
#    environment:
#      - ES_JAVA_OPTS=-Xms512m -Xmx512m
#      - discovery.type=single-node
#    volumes:
#      - /tmp/es-data:/usr/share/elasticsearch/data
#      - /tmp/es-plugins:/usr/share/elasticsearch/plugins
#    ports:
#      - 9200:9200
#      - 9300:9300
#    networks:
#      - es-net
#    privileged: yes
#  kibana:
#    container_name: kibana
#    image: kibana:7.12.1
#    environment:
#      - ELASTICSEARCH_HOSTS=http://es:9200
#    ports:
#      - 5601:5601
#    networks:
#      - es-net
  user-service:
    build: ./user-service
    ports:
    #  - "8722:8722"
      - "81:81"
    env_file:
      - ./web-variables.env
    volumes:
      - /tmp/logs/user:/logs
      - /tmp/logs/user/csp:/root/logs
  glycemia-service:
    build: ./glycemia-service
    ports:
      - "8721:8721"
      - "82:82"
    env_file:
      - ./web-variables.env
    volumes:
      - /tmp/logs/glycemia:/logs
      - /tmp/logs/glycemia/csp:/root/logs
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
      - "8719:8719"
    env_file:
      - ./web-variables.env
    volumes:
      - /tmp/logs/gateway:/logs
      - /tmp/logs/gateway/csp:/root/logs
  interact-service:
    build: ./interact-service
    ports:
      - "85:85"
      - "8724:8724"
    env_file:
      - ./web-variables.env
    volumes:
      - /tmp/logs/oa-service:/logs
      - /tmp/logs/oa-service/csp:/root/logs
  oa-service:
    build: ./oa-service
    ports:
      - "84:84"
      - "8723:8723"
    env_file:
      - ./web-variables.env
    volumes:
      - /tmp/logs/oa-service:/logs
      - /tmp/logs/oa-service/csp:/root/logs
  exercise-service:
    build: ./exercise-service
    ports:
    #  - "8720:8720"
      - "83:83"
    env_file:
      - ./web-variables.env
    volumes:
      - /tmp/logs/exercise:/logs
      - /tmp/logs/exercise/csp:/root/logs
networks:
  es-net:
    driver: bridge
